### PR TITLE
Update .env for cedar versions

### PR DESCRIPTION
**Pull request by benjag**

### CODE REVIEW

**Review by peripateticus — COMMENTED** [review]
Looks good @benjag! Just needs the version bump, RELEASE-NOTES update.

**Comment by benjag** [comment]
> Looks good @benjag! Just needs the version bump, RELEASE-NOTES update.

@peripateticus, what's your versioning strategy? Would you consider this a minor or a major?

**Comment by peripateticus** [comment]
> > Looks good @benjag! Just needs the version bump, RELEASE-NOTES update.
> 
> @peripateticus, what's your versioning strategy? Would you consider this a minor or a major?

I'm thinking minor.

**Review by peripateticus — APPROVED** [review]
Awesome, thank you for the update @benjag!

**Pull request merged**
